# Generated by Django 4.2.3 on 2023-10-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_remove_test_laboratory_remove_test_price_testprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='ownership',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
